SSH_USER: REPLACE_ME_WITH_SSH_USER
SSH_HOST: REPLACE_ME_WITH_SSH_HOST
REPORT_SITE_NAME: REPLACE_ME_WITH_SITE_NAME_FOR_REPORTS
REPORT_SITE_PATH: REPLACE_ME_WITH_SITE_ROOT_PATH_FOR_REPORTS
VISUAL_TEST_ZIP_URL: REPLACE_ME_WITH_VISUAL_TEST_ZIP_URL
