# For all other branches, the below block will be respected.
main:
  hostname: tr.rt.gw
  user: root
  site_url: https://utsav-ladani.tr.rt.gw
  main_site: utsav-ladani.tr.rt.gw
  deploy_path: /opt/easyengine/sites/utsav-ladani.tr.rt.gw/app/htdocs

multi_branch_env:
  hostname: tr.rt.gw
  user: root
  site_url: https://utsav-ladani.tr.rt.gw
  main_site: utsav-ladani.tr.rt.gw
  deploy_path: /opt/easyengine/sites/utsav-ladani.tr.rt.gw/app/htdocs