on: 
  pull_request:
    types: [ opened, synchronize ]
name: visual test on PR
jobs:
  visual_test_on_PR:
    name: Run visual test on PR
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Run visual test on PR Action
      uses: docker://ghcr.io/rtcamp/training-visual-test:v0.0.5
      env:
        GH_BOT_TOKEN: ${{ secrets.TRAINEE_RTBOT_TOKEN }}
        SSH_PRIVATE_KEY: ${{ secrets.TRAINEE_SSH_PRIVATE_KEY }}
        HTTP_AUTH_FOR_SITE: ${{ secrets.TRAINEE_HTTP_AUTH_FOR_SITE }}
        HTTP_AUTH_FOR_REPORTS: ${{ secrets.TRAINEE_HTTP_AUTH_FOR_SITE }}
    - name: Cleanup
      if: ${{ always() }}
      uses: rtCamp/action-cleanup@master
